# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'nyu-afr.xcworkspace'

target 'nyu-afr' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for nyu-afr

  target 'nyu-afrTests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'

  pod 'GoogleMaps'
  pod 'GooglePlaces'

end
